services:
  mysql:
    image: mysql:latest
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlineshopping
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/onlineshopping
    ports:
      - "3307:3306"
    networks:
      - microservices-network


  eureka-server:
    image: eureka-server-image
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    container_name: eureka-server

  user-service:
    image: user-image
    ports:
      - "8085:8085"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/onlineshopping
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka-server
      - mysql
    networks:
      - microservices-network
    container_name: user-service

  product-service:
    image: product-image
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/onlineshopping
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka-server
      - mysql
    networks:
      - microservices-network
    container_name: product-service

  category-service:
    image: category-image
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3306/onlineshopping
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka-server
      - mysql
    networks:
      - microservices-network
    container_name: category-service

  api-gateway:
    image: api-gateway-image
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - mysql
    networks:
      - microservices-network
    container_name: api-gateway

networks:
  microservices-network:
    driver: bridge
